Ext.define('wzqr.model.Application', {
    extend: 'wzqr.spring.data.Model',
    resourceURI: Utils.toApi('api/application'),
    /**
     * 是否未上报
     * */
    isWeishangbao: function() {
        return this.get('status') === '未上报';
    },
    /**
     * 是否是退回的
     * */
    isReturn: function() {
        return this.get('status').indexOf('退回') !== -1;
    },
    /**
     * 允许次级管理员编辑
     * */
    isBeableSubEdit: function() {
        return this.get('status') === '形审未过' || this.get('status') === '形审通过' || this.get('status') === '等待形审'
    },
    getmgenglish: function() {
        //中国, 温州大学, 物理, 博士
        var rs = '';
        if(this.get('mgEnglishCountry').length>0){
            rs =  rs + this.get('mgEnglishCountry') + ', ';
        }
        if(this.get('mgEnglishSchool').length>0){
            rs =  rs + this.get('mgEnglishSchool') + ', ';
        }
        if(this.get('mgEnglishSchool').length>0){
            rs =  rs + this.get('mgEnglishSchool') + ', ';
        }
        if(this.get('mgEnglishDegree').length>0){
            rs =  rs + this.get('mgEnglishDegree');
        }
        return rs;
    },
    getmgchina: function() {
        var rs = '';
        if(this.get('mgChineseCountry').length>0){
            rs =  rs + this.get('mgChineseCountry') + ', ';
        }
        if(this.get('mgChineseSchool').length>0){
            rs =  rs + this.get('mgChineseSchool') + ', ';
        }
        if(this.get('mgChineseMajor').length>0){
            rs =  rs + this.get('mgChineseMajor') + ', ';
        }
        if(this.get('mgChineseDegree').length>0){
            rs =  rs + this.get('mgChineseDegree');
        }
        return rs;
    },
    fields: [
        {name: 'owner', link: true},
        {name: 'myorg', link: true},
        {name: 'orgSubName', type: 'sstring'},
        {name: 'ownerLoginName', type: 'sstring'},
        {name: 'submitReason', type: 'sstring'},
        {name: 'submitSupport', type: 'sstring'},
        //创业人才
        {name: 'entInfo', type: 'sstring'},
        {name: 'entTeam', type: 'sstring'},
        {name: 'entProject', type: 'sstring'},
        {name: 'entPlan', type: 'sstring'},
        {name: 'actualCurrentFunds', type: 'sfloat'},
        {name: 'actualCurrentFundsPer', type: 'sfloat'},
        {name: 'myFundsPer', type: 'sfloat'},
        {name: 'actualFunds', type: 'sfloat'},
        {name: 'partnerName1', type: 'sstring'},
        {name: 'partnerName2', type: 'sstring'},
        {name: 'partnerName3', type: 'sstring'},
        {name: 'partnerName4', type: 'sstring'},
        {name: 'partnerName5', type: 'sstring'},
        {name: 'partnerName6', type: 'sstring'},
        {name: 'partnerName7', type: 'sstring'},
        {name: 'partnerName8', type: 'sstring'},
        {name: 'partnerName9', type: 'sstring'},
        {name: 'partnerName10', type: 'sstring'},
        {name: 'partnerName11', type: 'sstring'},
        {name: 'partnerName12', type: 'sstring'},
        {name: 'partnerName13', type: 'sstring'},
        {name: 'partnerName14', type: 'sstring'},
        {name: 'partnerName15', type: 'sstring'},
        {name: 'partnerName16', type: 'sstring'},
        {name: 'partnerName17', type: 'sstring'},
        {name: 'partnerName18', type: 'sstring'},
        {name: 'partnerName19', type: 'sstring'},
        {name: 'partnerName20', type: 'sstring'},
        {name: 'partnerContent1', type: 'sstring'},
        {name: 'partnerContent2', type: 'sstring'},
        {name: 'partnerContent3', type: 'sstring'},
        {name: 'partnerContent4', type: 'sstring'},
        {name: 'partnerContent5', type: 'sstring'},
        {name: 'partnerContent6', type: 'sstring'},
        {name: 'partnerContent7', type: 'sstring'},
        {name: 'partnerContent8', type: 'sstring'},
        {name: 'partnerContent9', type: 'sstring'},
        {name: 'partnerContent10', type: 'sstring'},
        {name: 'partnerContent11', type: 'sstring'},
        {name: 'partnerContent12', type: 'sstring'},
        {name: 'partnerContent13', type: 'sstring'},
        {name: 'partnerContent14', type: 'sstring'},
        {name: 'partnerContent15', type: 'sstring'},
        {name: 'partnerContent16', type: 'sstring'},
        {name: 'partnerContent17', type: 'sstring'},
        {name: 'partnerContent18', type: 'sstring'},
        {name: 'partnerContent19', type: 'sstring'},
        {name: 'partnerContent20', type: 'sstring'},
        {name: 'partnerType1', type: 'sstring'},
        {name: 'partnerType2', type: 'sstring'},
        {name: 'partnerType3', type: 'sstring'},
        {name: 'partnerType4', type: 'sstring'},
        {name: 'partnerType5', type: 'sstring'},
        {name: 'partnerType6', type: 'sstring'},
        {name: 'partnerType7', type: 'sstring'},
        {name: 'partnerType8', type: 'sstring'},
        {name: 'partnerType9', type: 'sstring'},
        {name: 'partnerType10', type: 'sstring'},
        {name: 'partnerType11', type: 'sstring'},
        {name: 'partnerType12', type: 'sstring'},
        {name: 'partnerType13', type: 'sstring'},
        {name: 'partnerType14', type: 'sstring'},
        {name: 'partnerType15', type: 'sstring'},
        {name: 'partnerType16', type: 'sstring'},
        {name: 'partnerType17', type: 'sstring'},
        {name: 'partnerType18', type: 'sstring'},
        {name: 'partnerType19', type: 'sstring'},
        {name: 'partnerType20', type: 'sstring'},
        {name: 'partnerPer1', type: 'sstring'},
        {name: 'partnerPer2', type: 'sstring'},
        {name: 'partnerPer3', type: 'sstring'},
        {name: 'partnerPer4', type: 'sstring'},
        {name: 'partnerPer5', type: 'sstring'},
        {name: 'partnerPer6', type: 'sstring'},
        {name: 'partnerPer7', type: 'sstring'},
        {name: 'partnerPer8', type: 'sstring'},
        {name: 'partnerPer9', type: 'sstring'},
        {name: 'partnerPer10', type: 'sstring'},
        {name: 'partnerPer11', type: 'sstring'},
        {name: 'partnerPer12', type: 'sstring'},
        {name: 'partnerPer13', type: 'sstring'},
        {name: 'partnerPer14', type: 'sstring'},
        {name: 'partnerPer15', type: 'sstring'},
        {name: 'partnerPer16', type: 'sstring'},
        {name: 'partnerPer17', type: 'sstring'},
        {name: 'partnerPer18', type: 'sstring'},
        {name: 'partnerPer19', type: 'sstring'},
        {name: 'partnerPer20', type: 'sstring'},
        {name: 'partnerPosition1', type: 'sstring'},
        {name: 'partnerPosition2', type: 'sstring'},
        {name: 'partnerPosition3', type: 'sstring'},
        {name: 'partnerPosition4', type: 'sstring'},
        {name: 'partnerPosition5', type: 'sstring'},
        {name: 'partnerPosition6', type: 'sstring'},
        {name: 'partnerPosition7', type: 'sstring'},
        {name: 'partnerPosition8', type: 'sstring'},
        {name: 'partnerPosition9', type: 'sstring'},
        {name: 'partnerPosition10', type: 'sstring'},
        {name: 'partnerPosition11', type: 'sstring'},
        {name: 'partnerPosition12', type: 'sstring'},
        {name: 'partnerPosition13', type: 'sstring'},
        {name: 'partnerPosition14', type: 'sstring'},
        {name: 'partnerPosition15', type: 'sstring'},
        {name: 'partnerPosition16', type: 'sstring'},
        {name: 'partnerPosition17', type: 'sstring'},
        {name: 'partnerPosition18', type: 'sstring'},
        {name: 'partnerPosition19', type: 'sstring'},
        {name: 'partnerPosition20', type: 'sstring'},
        //创业人才 end!
        {name: 'patentDesc', type: 'sstring'},
        {name: 'city', type: 'sstring'},
        {name: 'beforeOrg', type: 'sstring'},
        {name: 'beforePosition', type: 'sstring'},
        {name: 'borderDate', type: 'sstring'},
        {name: 'wdate', type: 'sstring'},
        {name: 'platform', type: 'sstring'},
        {name: 'poge', type: 'sboolean'},
        {name: 'comment', type: 'sstring'},
        {name: 'unitApproveReason', type: 'sstring'},
        {name: 'unitApproveSupport', type: 'sstring'},
        {name: 'pogeReason', type: 'sstring'},
        {name: 'orgApproveReason', type: 'sstring'},
        {name: 'orgApproveSupport', type: 'sstring'},
        {name: 'managerReason', type: 'sstring'},
        {name: 'returnOrg', type: 'sstring'},
        {name: 'returnReason', type: 'sstring'},
        {name: 'idType', type: 'sstring'},
        {name: 'idNumber', type: 'sstring'},
        {name: 'address', type: 'sstring'},
        {name: 'addressOut', type: 'sstring'},
        {name: 'phoneOut', type: 'sstring'},
        {name: 'email', type: 'sstring'},
        {name: 'personPhone', type: 'sstring'},
        {name: 'personMobile', type: 'sstring'},
        {name: 'relationship1', type: 'sstring'},
        {name: 'relationshipName1', type: 'sstring'},
        {name: 'relationshipAge1', type: 'sstring'},
        {name: 'relationshipCountry1', type: 'sstring'},
        {name: 'relationshipJob1', type: 'sstring'},
        {name: 'relationship2', type: 'sstring'},
        {name: 'relationshipName2', type: 'sstring'},
        {name: 'relationshipAge2', type: 'sstring'},
        {name: 'relationshipCountry2', type: 'sstring'},
        {name: 'relationshipJob2', type: 'sstring'},
        {name: 'relationship3', type: 'sstring'},
        {name: 'relationshipName3', type: 'sstring'},
        {name: 'relationshipAge3', type: 'sstring'},
        {name: 'relationshipCountry3', type: 'sstring'},
        {name: 'relationshipJob3', type: 'sstring'},
        {name: 'relationship4', type: 'sstring'},
        {name: 'relationshipName4', type: 'sstring'},
        {name: 'relationshipAge4', type: 'sstring'},
        {name: 'relationshipCountry4', type: 'sstring'},
        {name: 'relationshipJob4', type: 'sstring'},
        {name: 'relationship5', type: 'sstring'},
        {name: 'relationshipName5', type: 'sstring'},
        {name: 'relationshipAge5', type: 'sstring'},
        {name: 'relationshipCountry5', type: 'sstring'},
        {name: 'relationshipJob5', type: 'sstring'},
        {name: 'relationship6', type: 'sstring'},
        {name: 'relationshipName6', type: 'sstring'},
        {name: 'relationshipAge6', type: 'sstring'},
        {name: 'relationshipCountry6', type: 'sstring'},
        {name: 'relationshipJob6', type: 'sstring'},
        {name: 'relationship7', type: 'sstring'},
        {name: 'relationshipName7', type: 'sstring'},
        {name: 'relationshipAge7', type: 'sstring'},
        {name: 'relationshipCountry7', type: 'sstring'},
        {name: 'relationshipJob7', type: 'sstring'},
        {name: 'relationship8', type: 'sstring'},
        {name: 'relationshipName8', type: 'sstring'},
        {name: 'relationshipAge8', type: 'sstring'},
        {name: 'relationshipCountry8', type: 'sstring'},
        {name: 'relationshipJob8', type: 'sstring'},
        {name: 'relationship9', type: 'sstring'},
        {name: 'relationshipName9', type: 'sstring'},
        {name: 'relationshipAge9', type: 'sstring'},
        {name: 'relationshipCountry9', type: 'sstring'},
        {name: 'relationshipJob9', type: 'sstring'},
        {name: 'relationship10', type: 'sstring'},
        {name: 'relationshipName10', type: 'sstring'},
        {name: 'relationshipAge10', type: 'sstring'},
        {name: 'relationshipCountry10', type: 'sstring'},
        {name: 'relationshipJob10', type: 'sstring'},
        {name: 'paperTime1', type: 'sstring'},
        {name: 'paperTitle1', type: 'sstring'},
        {name: 'paperMedia1', type: 'sstring'},
        {name: 'paperAuthor1', type: 'sstring'},
        {name: 'paperTime2', type: 'sstring'},
        {name: 'paperTitle2', type: 'sstring'},
        {name: 'paperMedia2', type: 'sstring'},
        {name: 'paperAuthor2', type: 'sstring'},
        {name: 'paperTime3', type: 'sstring'},
        {name: 'paperTitle3', type: 'sstring'},
        {name: 'paperMedia3', type: 'sstring'},
        {name: 'paperAuthor3', type: 'sstring'},
        {name: 'paperTime4', type: 'sstring'},
        {name: 'paperTitle4', type: 'sstring'},
        {name: 'paperMedia4', type: 'sstring'},
        {name: 'paperAuthor4', type: 'sstring'},
        {name: 'paperTime5', type: 'sstring'},
        {name: 'paperTitle5', type: 'sstring'},
        {name: 'paperMedia5', type: 'sstring'},
        {name: 'paperAuthor5', type: 'sstring'},
        {name: 'paperTime6', type: 'sstring'},
        {name: 'paperTitle6', type: 'sstring'},
        {name: 'paperMedia6', type: 'sstring'},
        {name: 'paperAuthor6', type: 'sstring'},
        {name: 'paperTime7', type: 'sstring'},
        {name: 'paperTitle7', type: 'sstring'},
        {name: 'paperMedia7', type: 'sstring'},
        {name: 'paperAuthor7', type: 'sstring'},
        {name: 'paperTime8', type: 'sstring'},
        {name: 'paperTitle8', type: 'sstring'},
        {name: 'paperMedia8', type: 'sstring'},
        {name: 'paperAuthor8', type: 'sstring'},
        {name: 'paperTime9', type: 'sstring'},
        {name: 'paperTitle9', type: 'sstring'},
        {name: 'paperMedia9', type: 'sstring'},
        {name: 'paperAuthor9', type: 'sstring'},
        {name: 'paperTime10', type: 'sstring'},
        {name: 'paperTitle10', type: 'sstring'},
        {name: 'paperMedia10', type: 'sstring'},
        {name: 'paperAuthor10', type: 'sstring'},
        {name: 'paperTime11', type: 'sstring'},
        {name: 'paperTitle11', type: 'sstring'},
        {name: 'paperMedia11', type: 'sstring'},
        {name: 'paperAuthor11', type: 'sstring'},
        {name: 'paperTime12', type: 'sstring'},
        {name: 'paperTitle12', type: 'sstring'},
        {name: 'paperMedia12', type: 'sstring'},
        {name: 'paperAuthor12', type: 'sstring'},
        {name: 'paperTime13', type: 'sstring'},
        {name: 'paperTitle13', type: 'sstring'},
        {name: 'paperMedia13', type: 'sstring'},
        {name: 'paperAuthor13', type: 'sstring'},
        {name: 'paperTime14', type: 'sstring'},
        {name: 'paperTitle14', type: 'sstring'},
        {name: 'paperMedia14', type: 'sstring'},
        {name: 'paperAuthor14', type: 'sstring'},
        {name: 'paperTime15', type: 'sstring'},
        {name: 'paperTitle15', type: 'sstring'},
        {name: 'paperMedia15', type: 'sstring'},
        {name: 'paperAuthor15', type: 'sstring'},
        {name: 'paperTime16', type: 'sstring'},
        {name: 'paperTitle16', type: 'sstring'},
        {name: 'paperMedia16', type: 'sstring'},
        {name: 'paperAuthor16', type: 'sstring'},
        {name: 'paperTime17', type: 'sstring'},
        {name: 'paperTitle17', type: 'sstring'},
        {name: 'paperMedia17', type: 'sstring'},
        {name: 'paperAuthor17', type: 'sstring'},
        {name: 'paperTime18', type: 'sstring'},
        {name: 'paperTitle18', type: 'sstring'},
        {name: 'paperMedia18', type: 'sstring'},
        {name: 'paperAuthor18', type: 'sstring'},
        {name: 'paperTime19', type: 'sstring'},
        {name: 'paperTitle19', type: 'sstring'},
        {name: 'paperMedia19', type: 'sstring'},
        {name: 'paperAuthor19', type: 'sstring'},
        {name: 'paperTime20', type: 'sstring'},
        {name: 'paperTitle20', type: 'sstring'},
        {name: 'paperMedia20', type: 'sstring'},
        {name: 'paperAuthor20', type: 'sstring'},
        {name: 'patentTime1', type: 'sstring'},
        {name: 'patentName1', type: 'sstring'},
        {name: 'patentCountry1', type: 'sstring'},
        {name: 'patentAuthor1', type: 'sstring'},
        {name: 'patentTime2', type: 'sstring'},
        {name: 'patentName2', type: 'sstring'},
        {name: 'patentCountry2', type: 'sstring'},
        {name: 'patentAuthor2', type: 'sstring'},
        {name: 'patentTime3', type: 'sstring'},
        {name: 'patentName3', type: 'sstring'},
        {name: 'patentCountry3', type: 'sstring'},
        {name: 'patentAuthor3', type: 'sstring'},
        {name: 'patentTime4', type: 'sstring'},
        {name: 'patentName4', type: 'sstring'},
        {name: 'patentCountry4', type: 'sstring'},
        {name: 'patentAuthor4', type: 'sstring'},
        {name: 'patentTime5', type: 'sstring'},
        {name: 'patentName5', type: 'sstring'},
        {name: 'patentCountry5', type: 'sstring'},
        {name: 'patentAuthor5', type: 'sstring'},
        {name: 'patentTime6', type: 'sstring'},
        {name: 'patentName6', type: 'sstring'},
        {name: 'patentCountry6', type: 'sstring'},
        {name: 'patentAuthor6', type: 'sstring'},
        {name: 'patentTime7', type: 'sstring'},
        {name: 'patentName7', type: 'sstring'},
        {name: 'patentCountry7', type: 'sstring'},
        {name: 'patentAuthor7', type: 'sstring'},
        {name: 'patentTime8', type: 'sstring'},
        {name: 'patentName8', type: 'sstring'},
        {name: 'patentCountry8', type: 'sstring'},
        {name: 'patentAuthor8', type: 'sstring'},
        {name: 'patentTime9', type: 'sstring'},
        {name: 'patentName9', type: 'sstring'},
        {name: 'patentCountry9', type: 'sstring'},
        {name: 'patentAuthor9', type: 'sstring'},
        {name: 'patentTime10', type: 'sstring'},
        {name: 'patentName10', type: 'sstring'},
        {name: 'patentCountry10', type: 'sstring'},
        {name: 'patentAuthor10', type: 'sstring'},
        {name: 'patentTime11', type: 'sstring'},
        {name: 'patentName11', type: 'sstring'},
        {name: 'patentCountry11', type: 'sstring'},
        {name: 'patentAuthor11', type: 'sstring'},
        {name: 'patentTime12', type: 'sstring'},
        {name: 'patentName12', type: 'sstring'},
        {name: 'patentCountry12', type: 'sstring'},
        {name: 'patentAuthor12', type: 'sstring'},
        {name: 'patentTime13', type: 'sstring'},
        {name: 'patentName13', type: 'sstring'},
        {name: 'patentCountry13', type: 'sstring'},
        {name: 'patentAuthor13', type: 'sstring'},
        {name: 'patentTime14', type: 'sstring'},
        {name: 'patentName14', type: 'sstring'},
        {name: 'patentCountry14', type: 'sstring'},
        {name: 'patentAuthor14', type: 'sstring'},
        {name: 'patentTime15', type: 'sstring'},
        {name: 'patentName15', type: 'sstring'},
        {name: 'patentCountry15', type: 'sstring'},
        {name: 'patentAuthor15', type: 'sstring'},
        {name: 'patentTime16', type: 'sstring'},
        {name: 'patentName16', type: 'sstring'},
        {name: 'patentCountry16', type: 'sstring'},
        {name: 'patentAuthor16', type: 'sstring'},
        {name: 'patentTime17', type: 'sstring'},
        {name: 'patentName17', type: 'sstring'},
        {name: 'patentCountry17', type: 'sstring'},
        {name: 'patentAuthor17', type: 'sstring'},
        {name: 'patentTime18', type: 'sstring'},
        {name: 'patentName18', type: 'sstring'},
        {name: 'patentCountry18', type: 'sstring'},
        {name: 'patentAuthor18', type: 'sstring'},
        {name: 'patentTime19', type: 'sstring'},
        {name: 'patentName19', type: 'sstring'},
        {name: 'patentCountry19', type: 'sstring'},
        {name: 'patentAuthor19', type: 'sstring'},
        {name: 'patentTime20', type: 'sstring'},
        {name: 'patentName20', type: 'sstring'},
        {name: 'patentCountry20', type: 'sstring'},
        {name: 'patentAuthor20', type: 'sstring'},
        {name: 'product', type: 'sstring'},
        {name: 'otherProduct', type: 'sstring'},
        {name: 'objectives', type: 'sstring'},
        {name: 'agreement', type: 'sstring'},
        {name: 'jobPosition1', type: 'sstring'},
        {name: 'jobTime1', type: 'sstring'},
        {name: 'jobCountry1', type: 'sstring'},
        {name: 'jobOrg1', type: 'sstring'},
        {name: 'jobPosition2', type: 'sstring'},
        {name: 'jobTime2', type: 'sstring'},
        {name: 'jobCountry2', type: 'sstring'},
        {name: 'jobOrg2', type: 'sstring'},
        {name: 'jobPosition3', type: 'sstring'},
        {name: 'jobTime3', type: 'sstring'},
        {name: 'jobCountry3', type: 'sstring'},
        {name: 'jobOrg3', type: 'sstring'},
        {name: 'jobPosition4', type: 'sstring'},
        {name: 'jobTime4', type: 'sstring'},
        {name: 'jobCountry4', type: 'sstring'},
        {name: 'jobOrg4', type: 'sstring'},
        {name: 'jobPosition5', type: 'sstring'},
        {name: 'jobTime5', type: 'sstring'},
        {name: 'jobCountry5', type: 'sstring'},
        {name: 'jobOrg5', type: 'sstring'},
        {name: 'jobPosition6', type: 'sstring'},
        {name: 'jobTime6', type: 'sstring'},
        {name: 'jobCountry6', type: 'sstring'},
        {name: 'jobOrg6', type: 'sstring'},
        {name: 'jobPosition7', type: 'sstring'},
        {name: 'jobTime7', type: 'sstring'},
        {name: 'jobCountry7', type: 'sstring'},
        {name: 'jobOrg7', type: 'sstring'},
        {name: 'jobPosition8', type: 'sstring'},
        {name: 'jobTime8', type: 'sstring'},
        {name: 'jobCountry8', type: 'sstring'},
        {name: 'jobOrg8', type: 'sstring'},
        {name: 'jobPosition9', type: 'sstring'},
        {name: 'jobTime9', type: 'sstring'},
        {name: 'jobCountry9', type: 'sstring'},
        {name: 'jobOrg9', type: 'sstring'},
        {name: 'expertTo', type: 'sstring'},
        {name: 'projectTime1', type: 'sstring'},
        {name: 'projectDesc1', type: 'sstring'},
        {name: 'projectBudget1', type: 'sstring'},
        {name: 'projectPeoples1', type: 'sstring'},
        {name: 'projectResponsibility1', type: 'sstring'},
        {name: 'projectTime2', type: 'sstring'},
        {name: 'projectDesc2', type: 'sstring'},
        {name: 'projectBudget2', type: 'sstring'},
        {name: 'projectPeoples2', type: 'sstring'},
        {name: 'projectResponsibility2', type: 'sstring'},
        {name: 'projectTime3', type: 'sstring'},
        {name: 'projectDesc3', type: 'sstring'},
        {name: 'projectBudget3', type: 'sstring'},
        {name: 'projectPeoples3', type: 'sstring'},
        {name: 'projectResponsibility3', type: 'sstring'},
        {name: 'projectTime4', type: 'sstring'},
        {name: 'projectDesc4', type: 'sstring'},
        {name: 'projectBudget4', type: 'sstring'},
        {name: 'projectPeoples4', type: 'sstring'},
        {name: 'projectResponsibility4', type: 'sstring'},
        {name: 'projectTime5', type: 'sstring'},
        {name: 'projectDesc5', type: 'sstring'},
        {name: 'projectBudget5', type: 'sstring'},
        {name: 'projectPeoples5', type: 'sstring'},
        {name: 'projectResponsibility5', type: 'sstring'},
        {name: 'projectTime6', type: 'sstring'},
        {name: 'projectDesc6', type: 'sstring'},
        {name: 'projectBudget6', type: 'sstring'},
        {name: 'projectPeoples6', type: 'sstring'},
        {name: 'projectResponsibility6', type: 'sstring'},
        {name: 'projectTime7', type: 'sstring'},
        {name: 'projectDesc7', type: 'sstring'},
        {name: 'projectBudget7', type: 'sstring'},
        {name: 'projectPeoples7', type: 'sstring'},
        {name: 'projectResponsibility7', type: 'sstring'},
        {name: 'projectTime8', type: 'sstring'},
        {name: 'projectDesc8', type: 'sstring'},
        {name: 'projectBudget8', type: 'sstring'},
        {name: 'projectPeoples8', type: 'sstring'},
        {name: 'projectResponsibility8', type: 'sstring'},
        {name: 'projectTime9', type: 'sstring'},
        {name: 'projectDesc9', type: 'sstring'},
        {name: 'projectBudget9', type: 'sstring'},
        {name: 'projectPeoples9', type: 'sstring'},
        {name: 'projectResponsibility9', type: 'sstring'},
        {name: 'id', type: 'int'},
        {name: 'status', type: 'sstring'},
        {name: 'batch', type: 'sstring'},
        {name: 'type', type: 'sstring'},
        {name: 'specialty', type: 'sstring'},
        {name: 'profession', type: 'sstring'},
        {name: 'number', type: 'sstring'},
        {name: 'realName', type: 'sstring', noarray: true},
        {name: 'realEnglishName', type: 'sstring', noarray: true},
        {name: 'appOrgName', type: 'sstring'},
        {name: 'people', type: 'sstring'},
        {name: 'mobile', type: 'sstring'},
        {name: 'phone', type: 'sstring'},
        {name: 'comletionDate', type: 'sdate', dateFormat: 'time'},
        {name: 'sex', type: 'int'},
        {name: 'birthDate', type: 'sdate', dateFormat: 'time'},
        {name: 'submitDate', type: 'sdate', dateFormat: 'time'},
        {name: 'birthPlace', type: 'sstring'},
        {name: 'nationality', type: 'sstring'},
        {name: 'mgChineseCountry', type: 'sstring'},
        {name: 'mgChineseSchool', type: 'sstring'},
        {name: 'mgChineseMajor', type: 'sstring'},
        {name: 'mgChineseDegree', type: 'sstring'},
        {name: 'mgEnglishCountry', type: 'sstring'},
        {name: 'mgEnglishSchool', type: 'sstring'},
        {name: 'mgEnglishMajor', type: 'sstring'},
        {name: 'mgEnglishDegree', type: 'sstring'},
        {name: 'foreignJobChinese', type: 'sstring'},
        {name: 'foreignJobEnglish', type: 'sstring'},
        {name: 'employer', type: 'sstring'},
        {name: 'position', type: 'sstring'},
        {name: 'employerAddress', type: 'sstring'},
        {name: 'zip', type: 'sstring'},
        {name: 'degree1', type: 'sstring'},
        {name: 'time1', type: 'sstring'},
        {name: 'country1', type: 'sstring'},
        {name: 'university1', type: 'sstring'},
        {name: 'major1', type: 'sstring'},
        {name: 'degree2', type: 'sstring'},
        {name: 'time2', type: 'sstring'},
        {name: 'country2', type: 'sstring'},
        {name: 'university2', type: 'sstring'},
        {name: 'major2', type: 'sstring'},
        {name: 'degree3', type: 'sstring'},
        {name: 'time3', type: 'sstring'},
        {name: 'country3', type: 'sstring'},
        {name: 'university3', type: 'sstring'},
        {name: 'major3', type: 'sstring'},
        {name: 'degree4', type: 'sstring'},
        {name: 'time4', type: 'sstring'},
        {name: 'country4', type: 'sstring'},
        {name: 'university4', type: 'sstring'},
        {name: 'major4', type: 'sstring'},
        {name: 'degree5', type: 'sstring'},
        {name: 'time5', type: 'sstring'},
        {name: 'country5', type: 'sstring'},
        {name: 'university5', type: 'sstring'},
        {name: 'major5', type: 'sstring'},
        {name: 'degree6', type: 'sstring'},
        {name: 'time6', type: 'sstring'},
        {name: 'country6', type: 'sstring'},
        {name: 'university6', type: 'sstring'},
        {name: 'major6', type: 'sstring'},
        {name: 'degree7', type: 'sstring'},
        {name: 'time7', type: 'sstring'},
        {name: 'country7', type: 'sstring'},
        {name: 'university7', type: 'sstring'},
        {name: 'major7', type: 'sstring'}
    ]
});